name: tetris
author: Florian Jeger, Christoph Jeger, Matthias Steffen
version: 0.0.1
description: Library für das Spiel Tetris.

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
